core/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('send/message', 'Backend\Admin\ContactController@sendMail')->name('send.message');

//User Routes
Auth::routes(['verify' => true]);
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register/{user}', 'Auth\RegisterController@showRegistrationForm')->name('refer');

Route::group(['namespace' => 'Backend\User', 'as' => 'user.', 'middleware' =>
    ['auth:web', 'verified', 'preventBackHistory', 'demomode']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // Profile Routes
    Route::get('profile', 'ProfileController@index')->name('profile')->middleware('password.confirm');
    Route::put('profile-update', 'ProfileController@updateProfile')->name('profile.update');
    Route::put('profile-image-update', 'ProfileController@updateProfileImage')->name('profile.image.update');
    Route::put('password-update', 'ProfileController@updatePassword')->name('password.update');
    // Profile Routes End

    // Transfer Money
    Route::get('transfer/money', 'TransferController@index')->name('transfer');
    Route::post('transfer/money', 'TransferController@transfer')->name('transfer.money');
    // Transfer Money End

    Route::get('referred/users', 'DashboardController@refUsers')->name('referred.user');

    Route::get('refer/friend', 'ProfileController@referPage')->name('refer.friend');
    Route::post('referral/link/send', 'ProfileController@sendLink')->name('referral.link.send');

    Route::get('refer/bonus/all', 'TransactionController@index')->name('refer.bonus');
    Route::get('transfer/bonus/all', 'TransactionController@transferBonus')->name('transfer.bonus');

    Route::get('user/transaction/search', 'TransactionController@searchTransaction')->name('search.transaction');

    Route::get('notification/all', 'DashboardController@notifications')->name('notification.all');
});
//End User Routes

//Admin Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin\Authentication', 'as' => 'admin.', 'middleware' => ['preventBackHistory', 'adminauth']], function () {
    Route::get('login', 'AdminLoginController@showLoginForm')->name('login.page');
    Route::post('login', 'AdminLoginController@login')->name('login');

    // Forgot Password
    Route::get('password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email')->middleware('demomode');
    // Forgot Password End

    // Reset Password
    Route::get('password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'AdminResetPasswordController@reset')->name
    ('update.password')->middleware('demomode');
    // Reset Password End

});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin', 'as' => 'admin.', 'middleware' => ['auth:admin', 'adminauth', 'preventBackHistory', 'demomode']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('logout', 'Authentication\AdminLoginController@logout')->name('logout');

    Route::get('user/all', 'UserController@index')->name('user.index');
    Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
    Route::put('user/{id}/update', 'UserController@update')->name('user.update');
    Route::get('user/{id}/show', 'UserController@show')->name('user.show');
    Route::post('user/{id}', 'UserController@loginUsingId')->name('login.using.id');
    Route::post('user/{id}/activate', 'UserController@active')->name('user.activate');
    Route::post('user/{id}/deactivate', 'UserController@deactive')->name('user.deactivate');
    Route::put('user/{id}/update/password', 'UserController@updatePassword')->name('user.update.password');

    Route::get('user/manage/balance', 'TransactionController@manageBalance')->name('user.balance.manage.page');
    Route::post('user/balance/operation', 'TransactionController@balanceOperation')->name('user.balance.operation');

    Route::get('user/transaction/all', 'TransactionController@index')->name('user.transaction.all');
    Route::get('{user}/transaction', 'TransactionController@userTransaction')->name('user.specific.transaction');

    Route::get('site/setting', 'SettingController@index')->name('site.setting');
    Route::put('site/{id}/setting/update', 'SettingController@update')->name('site.setting.update');

    Route::get('interest/all', 'InterestController@index')->name('interest.all');
    Route::get('interest/create', 'InterestController@create')->name('interest.create');
    Route::put('interest/give/{id}', 'InterestController@give')->name('interest.give');
    Route::get('interest/{id}/edit', 'InterestController@edit')->name('interest.edit');
    Route::post('interest/store', 'InterestController@store')->name('interest.store');
    Route::put('interest/{id}/update', 'InterestController@update')->name('interest.update');
    Route::delete('interest/{id}/destroy', 'InterestController@destroy')->name('interest.destroy');
    Route::get('interest/transaction/all', 'InterestController@transactions')->name('interest.transactions');

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('profile-update', 'ProfileController@updateProfile')->name('profile.update');
    Route::put('profile-image-update', 'ProfileController@updateProfileImage')->name('profile.image.update');
    Route::put('password-update', 'ProfileController@updatePassword')->name('password.update');

    Route::get('referred/users', 'ReferController@index')->name('referred.users');
    Route::get('referral/users', 'ReferController@referralUsers')->name('referral.users');
    Route::get('referral/users/transactions', 'ReferController@referralTransactions')->name('referral.users.transactions');
    Route::get('referred/users/transactions', 'ReferController@referredTransactions')->name('referred.users.transactions');

    Route::get('ip/logs', 'TrackController@index')->name('user.track');


    Route::get('contact/all', 'ContactController@index')->name('contact.index');
    Route::get('contact/message/{id}/show', 'ContactController@show')
        ->name('show.message');
    Route::get('contact/message/{id}/send', 'ContactController@replySendMail')
        ->name('send.reply.message');
    Route::post('contact/message/{id}/reply', 'ContactController@replyMail')
        ->name('reply.message');


    Route::get('user/search', 'UserController@userSearch')->name('user.search');
    Route::get('user/referral/search', 'ReferController@referralUserSearch')->name('user.search.referral');
    Route::get('user/referred/search', 'ReferController@referredUserSearch')->name('user.search.referred');
    Route::get('user/transaction/search', 'TransactionController@transactionSearch')->name('user.search.transaction');
    Route::get('contact/search', 'ContactController@contactSearch')->name('search.contact');
});
//End Admin Routes

core/app/Models/Interest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Interest extends Model
{
    protected $guarded = [];

}

core/app/Http/Controllers/Backend/Admin/InterestController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use App\Mail\InterestMail;
use App\Models\Interest;
use App\Models\Setting;
use App\Models\Transaction;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

class InterestController extends Controller
{
    public function index()
    {
        $title = "All Interest";
        $interests = Interest::latest()->paginate(10);
        return view('backend.admin.interest.index', compact('interests', 'title'));
    }

    public function create()
    {
        $title = "Create Interest";
        return view('backend.admin.interest.create', compact('title'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'bail|required|string',
            'percent' => 'bail|required|numeric',
        ]);

        $interest = new Interest();
        $interest->name = $request->name;
        $interest->percent = $request->percent;
        $interest->save();
        return redirect()->route('admin.interest.all')->with('success', 'Interest added successfully');
    }

    public function edit($id)
    {
        $title = "Edit Interest";
        $interest = Interest::findOrFail($id);
        return view('backend.admin.interest.edit', compact('interest', 'title'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'bail|required|string',
            'percent' => 'bail|required|numeric',
        ]);

        $interest = Interest::findOrFail($id);
        $interest->name = $request->name;
        $interest->percent = $request->percent;
        $interest->save();
        return redirect()->route('admin.interest.all')->with('success', 'Interest updated successfully');
    }

    public function destroy($id)
    {
        $interest = Interest::findOrFail($id);
        $interest->delete();
        return back()->with('success', 'Interest deleted successfully');
    }

    public function give($id)
    {
        $interest = Interest::findOrFail($id);
        $users = User::all();
        $setting = Setting::first();

        if ($users->isEmpty()) {
            return back()->with('error', 'No user found');
        }
        foreach ($users as $user) {
            $current_balance = $user->balance;
            $give_interest = ($interest->percent * $current_balance) / 100;
            $new_balance = $current_balance + $give_interest;
            $user->balance = $new_balance;

            $trx = new Transaction();
            $trx->user_id = $user->id;
            $trx->trx_num = Str::random(12);
            $trx->trx_type = true;
            $trx->details = $give_interest . ' ' . $setting->currency . ' received ' . Str::lower($interest->name);
            $trx->amount = $give_interest;
            $trx->remaining_balance = $user->balance;
            $trx->interest = true;

            Mail::to($user)->send(new InterestMail($give_interest, $setting));
            sleep(1);

            $trx->save();
            $user->save();

        }
        return back()->with('success', "Interest successfully sent");
    }

    public function transactions()
    {
        $title = "Interest Transactions";
        $trxs = Transaction::where('interest', true)->latest()->paginate(10);
        return view('backend.admin.interest.interest_transactions', compact('trxs', 'title'));
    }

}

core/resources/views/backend/admin/interest/create.blade.php
@extends("layouts.backend.admin.app")


@section('breadcomb', $title)

@section("content")
    <div class="single-product-tab-area mg-b-30">

        <div class="single-pro-review-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="review-tab-pro-inner">
                            <ul id="myTab3" class="tab-review-design">
                                <li class="active">
                                    <a href="#profile"><i class="fa fa-plus"
                                                          aria-hidden="true"></i> {{ $title }}</a>
                                </li>
                            </ul>

                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="profile">

                                    <form action="{{ route('admin.interest.store') }}" method="POST">
                                        @csrf

                                        <div class="row">

                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-lg-offset-3">

                                                <div class="review-content-section">

                                                            <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-usd" aria-hidden="true"></i>
                                                        </span>
                                                                <input id="name" type="text" name="name"
                                                                       class="form-control"
                                                                       placeholder="Enter interest name"
                                                                       value="{{ old('name') }}">
                                                            </div>

                                                            <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-percent" aria-hidden="true"></i>
                                                        </span>
                                                                <input type="text" name="percent"
                                                                       class="form-control"
                                                                       placeholder="Enter interest percent"
                                                                       value="{{ old('percent') }}">
                                                            </div>


                                                        </div>

                                                </div>

                                                <div class="row">
                                                    <div
                                                        class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="text-center custom-pro-edt-ds">
                                                            <button title="Click to submit" type="submit"
                                                                    class="btn btn-ctl-bt waves-effect waves-light m-r-10">
                                                                Save
                                                            </button>
                                                            <button title="Click to go previous page" type="button"
                                                                    onclick="window.history.back();"
                                                                    class="btn btn-ctl-bt waves-effect waves-light"
                                                                    style="margin-top: 0;">
                                                                Discard
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>

                                        </div>
                                    </form>

                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

core/resources/views/backend/admin/interest/edit.blade.php
@extends("layouts.backend.admin.app")


@section('breadcomb', $title)

@section("content")
    <div class="single-product-tab-area mg-b-30">

        <div class="single-pro-review-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="review-tab-pro-inner">
                            <ul id="myTab3" class="tab-review-design">
                                <li class="active">
                                    <a href="#profile"><i class="fa fa-plus"
                                                          aria-hidden="true"></i> {{ $title }}</a>
                                </li>
                            </ul>

                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="profile">

                                    <form action="{{ route('admin.interest.update', $interest->id) }}" method="POST">
                                        @csrf
                                        @method("PUT")
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-lg-offset-3">
                                                <div class="review-content-section">

                                                    <div class="review-content-section">
                                                        <div class="review-content-section">
                                                            <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-usd" aria-hidden="true"></i>
                                                        </span>
                                                                <input id="name" type="text" name="name"
                                                                       class="form-control"
                                                                       placeholder="Enter interest name"
                                                                       value="{{ $interest->name ?? old('name') }}">
                                                            </div>

                                                            <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-percent" aria-hidden="true"></i>
                                                        </span>
                                                                <input type="text" name="percent"
                                                                       class="form-control"
                                                                       placeholder="Enter interest percent"
                                                                       value="{{ $interest->percent ?? old('percent') }}">
                                                            </div>


                                                        </div>
                                                    </div>

                                                </div>

                                                <div class="row">
                                                    <div
                                                        class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="text-center custom-pro-edt-ds">
                                                            <button title="Click to submit" type="submit"
                                                                    class="btn btn-ctl-bt waves-effect waves-light m-r-10">
                                                                Save
                                                            </button>
                                                            <button title="Click to go previous page" type="button"
                                                                    onclick="window.history.back();"
                                                                    class="btn btn-ctl-bt waves-effect waves-light"
                                                                    style="margin-top: 0;">
                                                                Discard
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>

                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

core/resources/views/backend/admin/interest/index.blade.php
@extends("layouts.backend.admin.app")


@section('breadcomb', $title)

@section("content")
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>Interest List</h4>
                        <div class="add-product">
                            <a title="Add interest" href="{{ route('admin.interest.create') }}">Add Interest</a>
                        </div>
                        <table>
                            <tr>
                                <th>Serial No</th>
                                <th>Name</th>
                                <th>Percent</th>
                                <th>Created AT</th>
                                <th>Updated AT</th>
                                <th>Action</th>
                            </tr>
                            @forelse($interests as $key => $interest)
                                <tr>

                                    <td>{{ $interests->firstItem()+$key }}</td>
                                    <td>{{ $interest->name }}</td>
                                    <td>{{ $interest->percent }}</td>
                                    <td>{{ $interest->created_at->diffForHumans() }}</td>
                                    <td>{{ $interest->updated_at->diffForHumans() }}</td>
                                    <td>
                                        <button title="Click to give interest to all users" onclick="giveInterest({{ $interest->id }})" class="btn btn-sm btn-warning waves-effect" type="button">
                                            <i style="font-size: 15px;" class="fa fa-check"></i>
                                            <form id="interest-form-{{ $interest->id }}" action="{{ route('admin.interest.give', $interest->id) }}" method="POST" style="display: none;">
                                                @csrf
                                                @method('PUT')
                                            </form>
                                        </button>

                                        <a title="Edit interest" class="btn btn-sm btn-info" href="{{ route('admin.interest.edit', $interest->id) }}">
                                            <i class="fa fa-edit"></i>
                                        </a>

                                        <button title="Delete interest" onclick="deleteItem({{ $interest->id }})" class="btn btn-danger waves-effect" type="button">
                                            <i style="font-size: 15px;" class="fa fa-trash"></i>
                                            <form id="delete-form-{{ $interest->id }}" action="{{ route('admin.interest.destroy', $interest->id) }}" method="POST" style="display: none;">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </button>

                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6">
                                        <h1 class="text-center">
                                            <span class="text-danger">{{ __('No interest found!!!') }}</span>
                                        </h1>
                                    </td>
                                </tr>
                            @endforelse

                        </table>
                        <div class="custom-pagination">
                            <ul class="pagination">
                                {{ $interests->links() }}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

core/resources/views/backend/admin/interest/interest_transactions.blade.php
@extends("layouts.backend.admin.app")

@section('breadcomb', $title)

@section("content")
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>{{ $title }}</h4>
                        <form action="{{ route('admin.user.search.transaction') }}" method="GET"
                              class="navbar-form navbar-right">
                            <div class="form-group">
                                <input type="text" name="query" class="form-control" placeholder="Search by trx num">
                            </div>
                        </form>
                        <table>
                            <tr>
                                <th>Serial No</th>
                                <th>TRX Num</th>
                                <th>Receiver</th>
                                <th>TRX Type</th>
                                <th>Amount</th>
                                <th>Remaining Balance</th>
                                <th>Interest</th>
                                <th>Details</th>
                            </tr>
                            @forelse($trxs as $key => $transaction)
                                <tr>

                                    <td>{{ $trxs->firstItem()+$key }}</td>
                                    <td>{{ $transaction->trx_num }}</td>
                                    <td>
                                        {{ $transaction->user->username }}
                                    </td>
                                    <td>{{ $transaction->trx_type }}</td>
                                    <td>{{ $transaction->amount }}</td>
                                    <td>{{ $transaction->remaining_balance }}</td>
                                    <td>
                                        @if($transaction->interest == true)
                                            <span class="badge badge-success">Received</span>
                                        @else
                                            <span class="badge badge-danger">Not Received</span>
                                        @endif
                                    </td>
                                    <td>{{ $transaction->details }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-info"
                                           href="{{ route('admin.user.specific.transaction', $transaction->user->slug) }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8">
                                        <h1 class="text-center">
                                            <span class="text-danger">{{ __('No transaction found!!!') }}</span>
                                        </h1>
                                    </td>
                                </tr>
                            @endforelse

                        </table>
                        <div class="custom-pagination">
                            <ul class="pagination">
                                {{ $trxs->links() }}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop