core/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('send/message', 'Backend\Admin\ContactController@sendMail')->name('send.message');

//User Routes
Auth::routes(['verify' => true]);
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register/{user}', 'Auth\RegisterController@showRegistrationForm')->name('refer');

Route::group(['namespace' => 'Backend\User', 'as' => 'user.', 'middleware' =>
    ['auth:web', 'verified', 'preventBackHistory', 'demomode']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // Profile Routes
    Route::get('profile', 'ProfileController@index')->name('profile')->middleware('password.confirm');
    Route::put('profile-update', 'ProfileController@updateProfile')->name('profile.update');
    Route::put('profile-image-update', 'ProfileController@updateProfileImage')->name('profile.image.update');
    Route::put('password-update', 'ProfileController@updatePassword')->name('password.update');
    // Profile Routes End

    // Transfer Money
    Route::get('transfer/money', 'TransferController@index')->name('transfer');
    Route::post('transfer/money', 'TransferController@transfer')->name('transfer.money');
    // Transfer Money End

    Route::get('referred/users', 'DashboardController@refUsers')->name('referred.user');

    Route::get('refer/friend', 'ProfileController@referPage')->name('refer.friend');
    Route::post('referral/link/send', 'ProfileController@sendLink')->name('referral.link.send');

    Route::get('refer/bonus/all', 'TransactionController@index')->name('refer.bonus');
    Route::get('transfer/bonus/all', 'TransactionController@transferBonus')->name('transfer.bonus');

    Route::get('user/transaction/search', 'TransactionController@searchTransaction')->name('search.transaction');

    Route::get('notification/all', 'DashboardController@notifications')->name('notification.all');
});
//End User Routes

//Admin Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin\Authentication', 'as' => 'admin.', 'middleware' => ['preventBackHistory', 'adminauth']], function () {
    Route::get('login', 'AdminLoginController@showLoginForm')->name('login.page');
    Route::post('login', 'AdminLoginController@login')->name('login');

    // Forgot Password
    Route::get('password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email')->middleware('demomode');
    // Forgot Password End

    // Reset Password
    Route::get('password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'AdminResetPasswordController@reset')->name
    ('update.password')->middleware('demomode');
    // Reset Password End

});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin', 'as' => 'admin.', 'middleware' => ['auth:admin', 'adminauth', 'preventBackHistory', 'demomode']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('logout', 'Authentication\AdminLoginController@logout')->name('logout');

    Route::get('user/all', 'UserController@index')->name('user.index');
    Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
    Route::put('user/{id}/update', 'UserController@update')->name('user.update');
    Route::get('user/{id}/show', 'UserController@show')->name('user.show');
    Route::post('user/{id}', 'UserController@loginUsingId')->name('login.using.id');
    Route::post('user/{id}/activate', 'UserController@active')->name('user.activate');
    Route::post('user/{id}/deactivate', 'UserController@deactive')->name('user.deactivate');
    Route::put('user/{id}/update/password', 'UserController@updatePassword')->name('user.update.password');

    Route::get('user/manage/balance', 'TransactionController@manageBalance')->name('user.balance.manage.page');
    Route::post('user/balance/operation', 'TransactionController@balanceOperation')->name('user.balance.operation');

    Route::get('user/transaction/all', 'TransactionController@index')->name('user.transaction.all');
    Route::get('{user}/transaction', 'TransactionController@userTransaction')->name('user.specific.transaction');

    Route::get('site/setting', 'SettingController@index')->name('site.setting');
    Route::put('site/{id}/setting/update', 'SettingController@update')->name('site.setting.update');

    Route::get('interest/all', 'InterestController@index')->name('interest.all');
    Route::get('interest/create', 'InterestController@create')->name('interest.create');
    Route::put('interest/give/{id}', 'InterestController@give')->name('interest.give');
    Route::get('interest/{id}/edit', 'InterestController@edit')->name('interest.edit');
    Route::post('interest/store', 'InterestController@store')->name('interest.store');
    Route::put('interest/{id}/update', 'InterestController@update')->name('interest.update');
    Route::delete('interest/{id}/destroy', 'InterestController@destroy')->name('interest.destroy');
    Route::get('interest/transaction/all', 'InterestController@transactions')->name('interest.transactions');

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('profile-update', 'ProfileController@updateProfile')->name('profile.update');
    Route::put('profile-image-update', 'ProfileController@updateProfileImage')->name('profile.image.update');
    Route::put('password-update', 'ProfileController@updatePassword')->name('password.update');

    Route::get('referred/users', 'ReferController@index')->name('referred.users');
    Route::get('referral/users', 'ReferController@referralUsers')->name('referral.users');
    Route::get('referral/users/transactions', 'ReferController@referralTransactions')->name('referral.users.transactions');
    Route::get('referred/users/transactions', 'ReferController@referredTransactions')->name('referred.users.transactions');

    Route::get('ip/logs', 'TrackController@index')->name('user.track');


    Route::get('contact/all', 'ContactController@index')->name('contact.index');
    Route::get('contact/message/{id}/show', 'ContactController@show')
        ->name('show.message');
    Route::get('contact/message/{id}/send', 'ContactController@replySendMail')
        ->name('send.reply.message');
    Route::post('contact/message/{id}/reply', 'ContactController@replyMail')
        ->name('reply.message');


    Route::get('user/search', 'UserController@userSearch')->name('user.search');
    Route::get('user/referral/search', 'ReferController@referralUserSearch')->name('user.search.referral');
    Route::get('user/referred/search', 'ReferController@referredUserSearch')->name('user.search.referred');
    Route::get('user/transaction/search', 'TransactionController@transactionSearch')->name('user.search.transaction');
    Route::get('contact/search', 'ContactController@contactSearch')->name('search.contact');
});
//End Admin Routes

core/resources/views/backend/admin/search/contact_search.blade.php
@extends("layouts.backend.admin.app")

@section('breadcomb', $title)

@section("content")
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>Search Result for:  {{ $title }}</h4>
                        <table>
                            <tr>
                                <th>Serial No</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Subject</th>
                                <th>Sent Time</th>
                                <th>Action</th>
                            </tr>
                            @forelse($contacts as $key => $contact)
                                <tr class="unread">
                                    <td>{{ ++$key }}</td>
                                    <td>{{ $contact->name }}</td>
                                    <td>{{ $contact->email }}</td>
                                    <td>{{ $contact->subject }}</td>
                                    <td>
                                        {{
                                        $contact->created_at->diffForHumans() }}
                                    </td>
                                    <td>
                                        <a class="btn btn-sm btn-info"
                                           title="Click to show details"
                                           href="{{ route('admin.show.message', $contact->id) }}">
                                            <i class="fa fa-eye"></i>
                                        </a>

                                        <a class="btn btn-sm btn-primary"
                                           title="Click to reply"
                                           href="{{ route('admin.send.reply.message', $contact->id)
                                           }}">
                                            <i class="fa fa-mail-reply"></i>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8">
                                        <h1 class="text-center">
                                            <span
                                                class="text-danger">{{ __('No
                                                 contact found!!!') }}</span>
                                        </h1>
                                    </td>
                                </tr>
                            @endforelse

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

core/resources/views/backend/admin/search/transaction_search.blade.php
@extends("layouts.backend.admin.app")



@section('breadcomb', "Search results for: ".$title)

@section("content")
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>Search results for: {{ $query }}</h4>
                        <table>
                            <tr>
                                <th>Serial No</th>
                                <th>TRX Num</th>
                                <th>Receiver</th>
                                <th>TRX Type</th>
                                <th>Amount</th>
                                <th>Remaining Balance</th>
                                <th>Details</th>
                            </tr>
                            @forelse($trxs as $key => $transaction)
                                <tr>

                                    <td>{{ ++$key }}</td>
                                    <td>{{ $transaction->trx_num }}</td>
                                    <td>
                                        {{ $transaction->user->username }}
                                    </td>
                                    <td>{{ $transaction->trx_type }}</td>
                                    <td>{{ $transaction->amount }}</td>
                                    <td>{{ $transaction->remaining_balance }}</td>
                                    <td>{{ $transaction->details }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-info"
                                           href="{{ route('admin.user.specific.transaction', $transaction->user->slug) }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8">
                                        <h1 class="text-center">
                                            <span class="text-danger">{{ __('No transaction found!!!') }}</span>
                                        </h1>
                                    </td>
                                </tr>
                            @endforelse

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

core/resources/views/backend/admin/search/user_search.blade.php
@extends("layouts.backend.admin.app")

@section('breadcomb', "Search result for: $title")

@section("content")
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>{{ $title }}</h4>
                        <table>
                            <tr>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Phone</th>
                                <th>Balance</th>
                                <th>Ref By</th>
                                <th>Joined</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            @if(!empty($user))
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->phone }}</td>
                                    <td>{{ number_format($user->balance, 2) }}</td>
                                    <td>
                                        @if(empty($user->user->name))
                                            <span
                                                class="text-danger">{{ __("Not found!!!") }}</span>
                                        @else
                                            {{ $user->user->name }}
                                        @endif
                                    </td>
                                    <td>{{ $user->created_at->diffForHumans() }}</td>
                                    <td>
                                        @if($user->status == 1)
                                            <span
                                                class="badge badge-success text-success">Active</span>
                                        @else
                                            <span class="badge badge-danger">Inactive</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a title="Click to edit user"
                                           class="btn btn-warning btn-sm"
                                           href="{{ route('admin.user.edit', $user->id) }}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a title="Click to show user information"
                                           class="btn btn-sm btn-info"
                                           href="{{ route('admin.user.show', $user->id) }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                </tr>
                            @else
                                <h3><span
                                        class="text-danger">{{ __('No user found!!!') }}</span>
                                </h3>
                            @endif

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop