core/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('send/message', 'Backend\Admin\ContactController@sendMail')->name('send.message');

//User Routes
Auth::routes(['verify' => true]);
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register/{user}', 'Auth\RegisterController@showRegistrationForm')->name('refer');

Route::group(['namespace' => 'Backend\User', 'as' => 'user.', 'middleware' =>
    ['auth:web', 'verified', 'preventBackHistory', 'demomode']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // Profile Routes
    Route::get('profile', 'ProfileController@index')->name('profile')->middleware('password.confirm');
    Route::put('profile-update', 'ProfileController@updateProfile')->name('profile.update');
    Route::put('profile-image-update', 'ProfileController@updateProfileImage')->name('profile.image.update');
    Route::put('password-update', 'ProfileController@updatePassword')->name('password.update');
    // Profile Routes End

    // Transfer Money
    Route::get('transfer/money', 'TransferController@index')->name('transfer');
    Route::post('transfer/money', 'TransferController@transfer')->name('transfer.money');
    // Transfer Money End

    Route::get('referred/users', 'DashboardController@refUsers')->name('referred.user');

    Route::get('refer/friend', 'ProfileController@referPage')->name('refer.friend');
    Route::post('referral/link/send', 'ProfileController@sendLink')->name('referral.link.send');

    Route::get('refer/bonus/all', 'TransactionController@index')->name('refer.bonus');
    Route::get('transfer/bonus/all', 'TransactionController@transferBonus')->name('transfer.bonus');

    Route::get('user/transaction/search', 'TransactionController@searchTransaction')->name('search.transaction');

    Route::get('notification/all', 'DashboardController@notifications')->name('notification.all');
});
//End User Routes

//Admin Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin\Authentication', 'as' => 'admin.', 'middleware' => ['preventBackHistory', 'adminauth']], function () {
    Route::get('login', 'AdminLoginController@showLoginForm')->name('login.page');
    Route::post('login', 'AdminLoginController@login')->name('login');

    // Forgot Password
    Route::get('password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email')->middleware('demomode');
    // Forgot Password End

    // Reset Password
    Route::get('password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'AdminResetPasswordController@reset')->name
    ('update.password')->middleware('demomode');
    // Reset Password End

});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin', 'as' => 'admin.', 'middleware' => ['auth:admin', 'adminauth', 'preventBackHistory', 'demomode']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('logout', 'Authentication\AdminLoginController@logout')->name('logout');

    Route::get('user/all', 'UserController@index')->name('user.index');
    Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
    Route::put('user/{id}/update', 'UserController@update')->name('user.update');
    Route::get('user/{id}/show', 'UserController@show')->name('user.show');
    Route::post('user/{id}', 'UserController@loginUsingId')->name('login.using.id');
    Route::post('user/{id}/activate', 'UserController@active')->name('user.activate');
    Route::post('user/{id}/deactivate', 'UserController@deactive')->name('user.deactivate');
    Route::put('user/{id}/update/password', 'UserController@updatePassword')->name('user.update.password');

    Route::get('user/manage/balance', 'TransactionController@manageBalance')->name('user.balance.manage.page');
    Route::post('user/balance/operation', 'TransactionController@balanceOperation')->name('user.balance.operation');

    Route::get('user/transaction/all', 'TransactionController@index')->name('user.transaction.all');
    Route::get('{user}/transaction', 'TransactionController@userTransaction')->name('user.specific.transaction');

    Route::get('site/setting', 'SettingController@index')->name('site.setting');
    Route::put('site/{id}/setting/update', 'SettingController@update')->name('site.setting.update');

    Route::get('interest/all', 'InterestController@index')->name('interest.all');
    Route::get('interest/create', 'InterestController@create')->name('interest.create');
    Route::put('interest/give/{id}', 'InterestController@give')->name('interest.give');
    Route::get('interest/{id}/edit', 'InterestController@edit')->name('interest.edit');
    Route::post('interest/store', 'InterestController@store')->name('interest.store');
    Route::put('interest/{id}/update', 'InterestController@update')->name('interest.update');
    Route::delete('interest/{id}/destroy', 'InterestController@destroy')->name('interest.destroy');
    Route::get('interest/transaction/all', 'InterestController@transactions')->name('interest.transactions');

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('profile-update', 'ProfileController@updateProfile')->name('profile.update');
    Route::put('profile-image-update', 'ProfileController@updateProfileImage')->name('profile.image.update');
    Route::put('password-update', 'ProfileController@updatePassword')->name('password.update');

    Route::get('referred/users', 'ReferController@index')->name('referred.users');
    Route::get('referral/users', 'ReferController@referralUsers')->name('referral.users');
    Route::get('referral/users/transactions', 'ReferController@referralTransactions')->name('referral.users.transactions');
    Route::get('referred/users/transactions', 'ReferController@referredTransactions')->name('referred.users.transactions');

    Route::get('ip/logs', 'TrackController@index')->name('user.track');


    Route::get('contact/all', 'ContactController@index')->name('contact.index');
    Route::get('contact/message/{id}/show', 'ContactController@show')
        ->name('show.message');
    Route::get('contact/message/{id}/send', 'ContactController@replySendMail')
        ->name('send.reply.message');
    Route::post('contact/message/{id}/reply', 'ContactController@replyMail')
        ->name('reply.message');


    Route::get('user/search', 'UserController@userSearch')->name('user.search');
    Route::get('user/referral/search', 'ReferController@referralUserSearch')->name('user.search.referral');
    Route::get('user/referred/search', 'ReferController@referredUserSearch')->name('user.search.referred');
    Route::get('user/transaction/search', 'TransactionController@transactionSearch')->name('user.search.transaction');
    Route::get('contact/search', 'ContactController@contactSearch')->name('search.contact');
});
//End Admin Routes

core/app/Http/Controllers/Backend/Admin/UserController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $title = "All Users";
        $users = User::with('user')->latest()->paginate(10);
        return view('backend.admin.user.index', compact('users', 'title'));
    }

    public function show($id)
    {
        $user = User::findOrFail($id);
        $title = $user->name . " Information";
        $transactions = $user->transactions()->paginate(10);
        $referredUsers = $user->referredusers()->paginate(10);
        return view('backend.admin.user.show', compact('user', 'transactions', 'referredUsers', 'title'));
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        $title = $user->name . ' Edit';
        return view('backend.admin.user.edit', compact('user', 'title'));
    }

    public function update(UserUpdateRequest $request, $id)
    {
        $request->validated();

        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->username = $request->username;
        $user->email = $request->email;
        $user->phone = $request->phone;
        $user->address = $request->address;
        $user->city = $request->city;
        $user->postcode = $request->postcode;
        $user->save();
        return redirect()->back()->with('success', 'User updated successfully');
    }

    public function updatePassword(Request $request, $id)
    {
        $request->validate([
            'password' => 'required|confirmed',
        ]);

        $user = User::findOrFail($id);
        $user->password = Hash::make($request->password);
        $user->save();
        return back()->with('success', 'Password reset successful');
    }

    public function loginUsingId($id)
    {
        $user = Auth::guard('web')->loginUsingId($id);
        if ($user->status == 0) {
            return back()->withInput()->with('error', 'Inactive user');
        }
        return redirect()->route('user.dashboard')->with('success', 'Login successful as ' . Auth::guard('web')->user()->name);
    }

    public function active($id)
    {
        $user = User::findOrFail($id);
        if ($user->status != false) {
            return back()->with('error', 'User is already been activated');
        }
        $user->status = true;
        $user->save();
        return back()->with('success', 'User has been activated');
    }

    public function deactive($id)
    {
        $user = User::findOrFail($id);
        if ($user->status != true) {
            return back()->with('error', 'User is already been deactivated');
        }
        $user->status = false;
        $user->save();
        return back()->with('success', 'User has been deactivated');
    }

    public function userSearch(Request $request)
    {
        $request->validate([
            'query' => 'bail|required|string'
        ]);
        $query = $request->input('query');
        $title = $query;
        $user = User::where('username', $query)->first();
        if (!$user) {
            return back()->with('error', 'User doesn\'t exists!!!');
        }
        return view('backend.admin.search.user_search', compact('query', 'user', 'title'));
    }
}

core/app/Http/Controllers/Backend/User/DashboardController.php
<?php

namespace App\Http\Controllers\Backend\User;

use App\Http\Controllers\Controller;
use App\Models\Bonus;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    public function index()
    {
        $data['user'] = Auth::user();
        $data['transactions'] = $data['user']->transactions()->latest()->paginate(10);
        $data['total_transaction'] = $data['user']->transactions()->sum('amount');
        $data['total_send_money'] = $data['user']->transactions()->where('trx_type', 0)->sum('amount');
        $data['refer_bonus'] = Bonus::where('user_id', $data['user']->id)->sum('refer_bonus');
        $data['transfer_bonus'] = Bonus::where('user_id', $data['user']->id)->sum('transfer_bonus');
        $data['total_bonus'] = $data['refer_bonus'] + $data['transfer_bonus'];
        $data['title'] = 'User Dashboard';
        return view('backend.user.dashboard')->with($data);
    }

    public function refUsers()
    {
        $refUsers = Auth::user()->referredusers()->latest()->with('user')->paginate(10);
        $title = "Referred Users";
        return view('backend.user.referred_user', compact('refUsers', 'title'));
    }

    public function notifications()
    {
        $title = "All notification";
        return view('backend.user.notifications', compact('title'));
    }


}

core/app/Http/Controllers/Backend/User/ProfileController.php
<?php

namespace App\Http\Controllers\Backend\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Models\Setting;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class ProfileController extends Controller
{
    public function index()
    {
        $title = "User Profile";
        return view('backend.user.profile', compact('title'));
    }

    public function updateProfile(UserRequest $request)
    {
        $request->validated();
        $user = User::findOrFail(Auth::id());
        $user->name = $request->name;
        $user->username = Auth::user()->username;
        $user->email = Auth::user()->email;
        $user->phone = $request->phone;
        $user->address = $request->address;
        $user->city = $request->city;
        $user->postcode = $request->postcode;
        $subject = "Profile updation notification";
        $message = view('emails.profile_update');
        sendMail(Auth::user()->email, $subject, $message);
        $user->save();
        return back()->with('success', 'User profile has been successfully updated');

    }

    public function updateProfileImage(Request $request)
    {
        $request->validate([
            "image" => "bail|image|max:3096",
        ], [
            "image.max" => "Maximum file size to upload is 3MB (3096 KB). If you are uploading a photo, try to reduce its resolution to make it under 3MB",
        ]);

        $user = User::findOrFail(Auth::id());
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $slug = Str::slug(Auth::user()->username);
            $currentDate = Carbon::now()->toDateString();
            $imagename = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            if (!file_exists('assets/uploads/profile')) {
                mkdir('assets/uploads/profile', 0777, true);
            }
            if (file_exists('assets/uploads/profile/' . $user->image)) {
                unlink('assets/uploads/profile/' . $user->image);
            }
            Image::make($image)->resize(300, 200)->save('assets/uploads/profile/' . $imagename);

        } else {
            $imagename = $user->image;
        }
        $user->image = $imagename;
        $user->save();
        return back()->with('success', 'User image successfully updated');
    }

    public function updatePassword(Request $request)
    {
        $validate = Validator::make($request->all(), [
            'old_password' => 'required',
            'password' => 'required|confirmed',
        ]);
        if ($validate->fails()) {
            return back()->with('error', $validate->messages()->all()[0])->withInput();
        }

        $hashedPassword = Auth::user()->getAuthPassword();
        if (!Hash::check($request->old_password, $hashedPassword)) {
            return back()->with("error", "Current password does not matched!!!");
        }
        if (Hash::check($request->password, $hashedPassword)) {
            return back()->with("error", "New password can't be the same as old password!");
        }
        $user = User::findOrFail(Auth::id());
        $user->password = Hash::make($request->password);
        $user->save();
        Session::flash('success', 'User password successfully changed');
        return redirect(route('login'))->with(Auth::logout());
    }

    public function referPage()
    {
        $title = "Refer a friend";
        return view('backend.user.refer', compact('title'));
    }

    public function sendLink(Request $request)
    {
        $request->validate([
            'refer_link' => 'bail|required|email',
        ]);
        $subject = "Join Online Wallet System by this link";
        $message = view('emails.refer_mail');
        sendMail($request->refer_link, $subject, $message, Auth::user()->email);
        return back()->with('success', "Referral link sent successfully");
    }
}

core/resources/views/backend/admin/user/referral_users_transactions.blade.php
@extends("layouts.backend.admin.app")

@section('breadcomb', $title)

@section("content")
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>{{ $title }}</h4>
                        <form action="{{ route('admin.user.search.transaction') }}" method="GET" class="navbar-form navbar-right">
                            <div class="form-group">
                                <input type="text" name="query" class="form-control" placeholder="Search by trx num">
                            </div>
                        </form>
                        <table>
                            <tr>
                                <th>Serial No</th>
                                <th>TRX Num</th>
                                <th>Receiver</th>
                                <th>TRX Type</th>
                                <th>Amount</th>
                                <th>Remaining Balance</th>
                                <th>Details</th>
                            </tr>
                            @forelse($trans as $key => $transaction)
                                <tr>

                                    <td>{{ $trans->firstItem()+$key }}</td>
                                    <td>{{ $transaction->trx_num }}</td>
                                    <td>
                                        {{ $transaction->user->username }}
                                    </td>
                                    <td>{{ $transaction->trx_type }}</td>
                                    <td>{{ $transaction->amount }}</td>
                                    <td>{{ $transaction->remaining_balance }}</td>
                                    <td>{{ $transaction->details }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-info"
                                           href="{{ route('admin.user.specific.transaction', $transaction->user->slug) }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8">
                                        <h1 class="text-center">
                                            <span class="text-danger">{{ __('No transaction found!!!') }}</span>
                                        </h1>
                                    </td>
                                </tr>
                            @endforelse

                        </table>
                        <div class="custom-pagination">
                            <ul class="pagination">
                                {{ $trans->links() }}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

core/resources/views/backend/admin/user/show.blade.php
@extends("layouts.backend.admin.app")

@section('breadcomb', $title)

@section("content")
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    <p class="text-center">
                                        <img style="width: 20%" class="img-thumbnail img-responsive img-circle"
                                             src="{{ asset('assets/uploads/profile/'.$user->image) }}"
                                             alt="{{ $user->username }}">
                                    </p>
                                    <h1 class="text-center">{{ $user->name }}</h1>
                                    <h3 class="text-center"> {{ $user->username }}</h3>
                                    <h4 class="text-center">
                                        Remaining Balance: {{ number_format($user->balance, 2) }}
                                    </h4>
                                    <p class="text-center">
                                        <a class="btn btn-primary" href="{{ route('admin.user.balance.manage.page') }}">Manage Balance</a>
                                        <button title="Login to this user" onclick="loginUser({{ $user->id }})" class="btn btn-info waves-effect" type="button">
                                            Login as user
                                            <i style="font-size: 15px;" class="fa fa-arrow-right"></i>
                                            <form id="login-form-{{ $user->id }}" action="{{ route('admin.login.using.id', $user->id) }}" method="POST" style="display: none;">
                                                @csrf
                                            </form>
                                        </button>

                                        @if($user->status == 1)
                                            <button title="Click to deactivate"
                                                    onclick="deactivateUser({{ $user->id }})"
                                                    class="btn btn-danger
                                                    waves-effect" type="button">
                                                Deactivate User
                                                <i style="font-size: 15px;" class="fa fa-arrow-right"></i>
                                                <form id="deactive-form-{{
                                                $user->id }}" action="{{
                                                route('admin.user.deactivate',
                                                 $user->id) }}"
                                                      method="POST" style="display: none;">
                                                    @csrf
                                                </form>
                                            </button>
                                        @else
                                            <button title="Click to activate"
                                                    onclick="activeUser
                                                        ({{ $user->id }})"
                                                    class="btn btn-success
                                                    waves-effect" type="button">
                                                Activate User
                                                <i style="font-size: 15px;" class="fa fa-arrow-right"></i>
                                                <form id="active-form-{{
                                                $user->id }}" action="{{
                                                route('admin.user.activate', $user->id) }}"
                                                      method="POST" style="display: none;">
                                                    @csrf
                                                </form>
                                            </button>
                                        @endif
                                    </p>
                                </div>
                                <div class="panel-body text-justify">
                                    <h3 class="well">Email: {{ $user->email }}</h3>
                                    <h3 class="well">Phone Number: {{ $user->phone }}</h3>
                                    <h3 class="well">Address: {{ $user->address }}</h3>
                                    <h3 class="well">City: {{ $user->city }}</h3>
                                    <h3 class="well">Postal Code: {{ $user->postcode }}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h1>
                                Transactions
                            </h1>
                        </div>
                        <div class="panel-body">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Serial No</th>
                                    <th>TRX Num</th>
                                    <th>Sender</th>
                                    <th>TRX Type</th>
                                    <th>Amount</th>
                                    <th>Remaining Balance</th>
                                    <th>Details</th>
                                    <th>Time & Date</th>
                                </tr>
                                @forelse($transactions as $key => $transaction)
                                    <tr>

                                        <td>{{ $transactions->firstItem()+$key }}</td>
                                        <td>{{ $transaction->trx_num }}</td>
                                        <td>{{ $transaction->user->username }}</td>
                                        <td>{{ $transaction->trx_type }}</td>
                                        <td>{{ $transaction->amount }}</td>
                                        <td>{{ $transaction->remaining_balance }}</td>
                                        <td>{{ $transaction->details }}</td>
                                        <td>{{ $transaction->created_at->diffForHumans() }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8">
                                            <h1 class="text-center">
                                                <span class="text-danger">{{ __('No transaction found!!!') }}</span>
                                            </h1>
                                        </td>
                                    </tr>
                                @endforelse

                            </table>
                            <div class="custom-pagination">
                                <ul class="pagination">
                                    {{ $transactions->links() }}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h1>Referred Users</h1>
                        </div>
                        <div class="panel-body">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Serial No</th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Phone</th>
                                    <th>Balance</th>
                                    <th>Ref By</th>
                                    <th>Action</th>
                                </tr>
                                @forelse($referredUsers as $key => $user)
                                    <tr>
                                        <td>{{ $referredUsers->firstItem()+$key }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->username }}</td>
                                        <td>{{ $user->phone }}</td>
                                        <td>{{ number_format($user->balance, 2) }}</td>
                                        <td>
                                            @if(empty($user->user->name))
                                                <span class="text-danger">{{ __("Not found!!!") }}</span>
                                            @else
                                                {{ $user->user->name }}
                                            @endif
                                        </td>
                                        <td>
                                            <a class="btn btn-warning btn-sm"
                                               href="{{ route('admin.user.edit', $user->id) }}">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-sm btn-info"
                                               href="{{ route('admin.user.show', $user->id) }}">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8">
                                            <h1 class="text-center">
                                                <span class="text-danger">{{ __('No user found!!!') }}</span>
                                            </h1>
                                        </td>
                                    </tr>
                                @endforelse

                            </table>
                            <div class="custom-pagination">
                                <ul class="pagination">
                                    {{ $referredUsers->links() }}
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@stop